export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const CLEAR_LEADERBOARD = 'CLEAR_LEADERBOARD';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
